import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { computeDeletionPlan, whyAlive } from "../../core/analysis/index.js";
import { symbolId } from "../../core/ir/index.js";
import { analyzeRustProjectWithGraph } from "./analyze.js";

const roots: string[] = [];

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describe("Rust frontend", () => {
  it("roots one exact private operation without hiding a compiler-confirmed sibling", async () => {
    const root = await mkdtemp(join(tmpdir(), "unused-rust-entry-symbol-"));
    roots.push(root);
    await mkdir(join(root, "src"), { recursive: true });
    await writeFile(
      join(root, "Cargo.toml"),
      '[package]\nname = "neutral-entry-symbol"\nversion = "0.1.0"\nedition = "2024"\n',
    );
    await writeFile(
      join(root, "Cargo.lock"),
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "neutral-entry-symbol"\nversion = "0.1.0"\n',
    );
    await writeFile(
      join(root, "src", "lib.rs"),
      "fn configured_operation() {}\nfn unused_sibling() {}\n",
    );
    await writeFile(
      join(root, "unused.config.jsonc"),
      JSON.stringify({
        entrySymbols: [
          {
            language: "rs",
            file: "src/lib.rs",
            name: "configured_operation",
            reason: "NIF operation",
          },
        ],
      }),
    );

    const analysis = await analyzeRustProjectWithGraph(root, { now: new Date(0) });
    expect(analysis.result.claims.map((claim) => claim.subject.name)).toEqual(["unused_sibling"]);
    expect(
      whyAlive({
        graph: analysis.graph,
        reachability: analysis.reachability,
        claims: analysis.result.claims,
        query: "configured_operation",
      }),
    ).toMatchObject({
      outcome: "alive",
      paths: [
        {
          entrypointReason: "NIF operation",
          hops: [{ file: "src/lib.rs", symbol: "configured_operation" }],
        },
      ],
    });
    expect(
      computeDeletionPlan({
        graph: analysis.graph,
        reachability: analysis.reachability,
        subject: { kind: "export", file: "src/lib.rs", name: "configured_operation" },
      }),
    ).toMatchObject({
      supported: false,
      unsupportedReason: expect.stringContaining("NIF operation"),
    });
  });

  it("claims only the compiler-confirmed private function and keeps public API alive", async () => {
    const root = await mkdtemp(join(tmpdir(), "unused-rust-analyze-"));
    roots.push(root);
    await mkdir(join(root, "src"), { recursive: true });
    await writeFile(
      join(root, "Cargo.toml"),
      '[package]\nname = "neutral-rust"\nversion = "0.1.0"\nedition = "2024"\n',
    );
    await writeFile(
      join(root, "Cargo.lock"),
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "neutral-rust"\nversion = "0.1.0"\n',
    );
    await writeFile(join(root, "src", "lib.rs"), "pub fn public_api() {}\nfn dead_helper() {}\n");

    const analysis = await analyzeRustProjectWithGraph(root, { now: new Date(0) });

    expect(analysis.result.claims).toMatchObject([
      {
        subject: { kind: "export", name: "dead_helper", loc: { file: "src/lib.rs", span: [2, 2] } },
        verdict: "unused",
        confidence: "high",
        evidence: [{ source: "rustc-dead-code" }],
        provenance: { analyzer: "rust-reference-graph" },
      },
    ]);
    expect(
      analysis.reachability.production.reachableSymbols.has(symbolId("src/lib.rs", "public_api")),
    ).toBe(true);
    expect(
      analysis.reachability.production.reachableSymbols.has(symbolId("src/lib.rs", "dead_helper")),
    ).toBe(false);
    expect(
      whyAlive({
        graph: analysis.graph,
        reachability: analysis.reachability,
        claims: analysis.result.claims,
        query: "dead_helper",
      }),
    ).toMatchObject({
      outcome: "dead",
      confidence: "high",
      evidence: [{ source: "rustc-dead-code" }],
    });
    expect(
      whyAlive({
        graph: analysis.graph,
        reachability: analysis.reachability,
        claims: analysis.result.claims,
        query: "public_api",
      }),
    ).toMatchObject({ outcome: "alive", entrypointKind: "production" });
  });

  it("keeps attributed runtime/linkage functions conservatively alive", async () => {
    const root = await mkdtemp(join(tmpdir(), "unused-rust-linkage-"));
    roots.push(root);
    await mkdir(join(root, "src"), { recursive: true });
    await writeFile(
      join(root, "Cargo.toml"),
      '[package]\nname = "neutral-linkage"\nversion = "0.1.0"\nedition = "2024"\n',
    );
    await writeFile(
      join(root, "Cargo.lock"),
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "neutral-linkage"\nversion = "0.1.0"\n',
    );
    await writeFile(
      join(root, "src", "lib.rs"),
      [
        "#[allow(dead_code)]",
        "#[unsafe(no_mangle)]",
        'unsafe extern "C" fn runtime_entry() {}',
        "",
        "#[inline]",
        "fn attributed_dead() {}",
        "",
      ].join("\n"),
    );

    const analysis = await analyzeRustProjectWithGraph(root, { now: new Date(0) });

    expect(analysis.result.claims).toEqual([]);
  });
});
