import { mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { computeDeletionPlan, whyAlive } from "../../core/analysis/index.js";
import { symbolId } from "../../core/ir/index.js";
import { analyzeRustProjectWithGraph, cargoUnits } from "./analyze.js";
import type { CargoPackage, CargoWorkspace } from "./metadata.js";

const roots: string[] = [];

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describe("Rust frontend", () => {
  it("orders non-ASCII Cargo units by locale-independent code units", () => {
    const root = "/neutral";
    const packages: CargoPackage[] = [
      cargoPackage("root", join(root, "Cargo.toml")),
      cargoPackage("lower", join(root, "crates", "äther", "Cargo.toml")),
      cargoPackage("upper", join(root, "crates", "Ångstrom", "Cargo.toml")),
      cargoPackage("ascii", join(root, "crates", "Zeta", "Cargo.toml")),
    ];
    const workspace: CargoWorkspace = {
      workspaceRoot: root,
      targetDirectory: join(root, "target"),
      packages,
      workspaceMemberIds: new Set(packages.map((pkg) => pkg.id)),
    };

    expect(cargoUnits(root, workspace)).toEqual([
      { rootRelDir: "", name: "root" },
      { rootRelDir: "crates/Zeta", name: "ascii" },
      { rootRelDir: "crates/Ångstrom", name: "upper" },
      { rootRelDir: "crates/äther", name: "lower" },
    ]);
  });

  it("retains realpath containment for prepartitioned source descriptors", async () => {
    const root = await mkdtemp(join(tmpdir(), "unused-rust-source-descriptor-"));
    const external = await mkdtemp(join(tmpdir(), "unused-rust-source-external-"));
    roots.push(root, external);
    await mkdir(join(root, "src"), { recursive: true });
    await writeFile(
      join(root, "Cargo.toml"),
      '[package]\nname = "neutral-descriptor"\nversion = "0.1.0"\nedition = "2024"\n',
    );
    await writeFile(
      join(root, "Cargo.lock"),
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "neutral-descriptor"\nversion = "0.1.0"\n',
    );
    const source = join(root, "src", "lib.rs");
    const insideAlias = join(root, "inside-alias.rs");
    const outsideAlias = join(root, "outside-alias.rs");
    await writeFile(source, "pub fn public_api() {}\n");
    await writeFile(join(external, "escaped.rs"), "fn escaped() {}\n");
    await symlink(source, insideAlias);
    await symlink(join(external, "escaped.rs"), outsideAlias);

    const analysis = await analyzeRustProjectWithGraph(
      root,
      { now: new Date(0) },
      { sourceFiles: [insideAlias, outsideAlias] },
    );

    expect(analysis.result.fileCount).toBe(1);
    expect(analysis.claimInputs.analysisFiles).toEqual(new Set(["src/lib.rs"]));
  });

  it("roots one exact private operation without hiding a compiler-confirmed sibling", async () => {
    const root = await mkdtemp(join(tmpdir(), "unused-rust-entry-symbol-"));
    roots.push(root);
    await mkdir(join(root, "src"), { recursive: true });
    await writeFile(
      join(root, "Cargo.toml"),
      '[package]\nname = "neutral-entry-symbol"\nversion = "0.1.0"\nedition = "2024"\n',
    );
    await writeFile(
      join(root, "Cargo.lock"),
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "neutral-entry-symbol"\nversion = "0.1.0"\n',
    );
    await writeFile(
      join(root, "src", "lib.rs"),
      "fn configured_operation() {}\nfn unused_sibling() {}\n",
    );
    await writeFile(
      join(root, "unused.config.jsonc"),
      JSON.stringify({
        entrySymbols: [
          {
            language: "rs",
            file: "src/lib.rs",
            name: "configured_operation",
            reason: "NIF operation",
          },
        ],
      }),
    );

    const analysis = await analyzeRustProjectWithGraph(root, { now: new Date(0) });
    expect(analysis.result.claims.map((claim) => claim.subject.name)).toEqual(["unused_sibling"]);
    expect(
      whyAlive({
        graph: analysis.graph,
        reachability: analysis.reachability,
        claims: analysis.result.claims,
        query: "configured_operation",
      }),
    ).toMatchObject({
      outcome: "alive",
      paths: [
        {
          entrypointReason: "NIF operation",
          hops: [{ file: "src/lib.rs", symbol: "configured_operation" }],
        },
      ],
    });
    expect(
      computeDeletionPlan({
        graph: analysis.graph,
        reachability: analysis.reachability,
        subject: { kind: "export", file: "src/lib.rs", name: "configured_operation" },
      }),
    ).toMatchObject({
      supported: false,
      unsupportedReason: expect.stringContaining("NIF operation"),
    });
  });

  it("claims only the compiler-confirmed private function and keeps public API alive", async () => {
    const root = await mkdtemp(join(tmpdir(), "unused-rust-analyze-"));
    roots.push(root);
    await mkdir(join(root, "src"), { recursive: true });
    await writeFile(
      join(root, "Cargo.toml"),
      '[package]\nname = "neutral-rust"\nversion = "0.1.0"\nedition = "2024"\n',
    );
    await writeFile(
      join(root, "Cargo.lock"),
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "neutral-rust"\nversion = "0.1.0"\n',
    );
    await writeFile(join(root, "src", "lib.rs"), "pub fn public_api() {}\nfn dead_helper() {}\n");

    const analysis = await analyzeRustProjectWithGraph(root, { now: new Date(0) });

    expect(analysis.result.claims).toMatchObject([
      {
        subject: { kind: "export", name: "dead_helper", loc: { file: "src/lib.rs", span: [2, 2] } },
        verdict: "unused",
        confidence: "high",
        evidence: [{ source: "rustc-dead-code" }],
        provenance: { analyzer: "rust-reference-graph" },
      },
    ]);
    expect(
      analysis.reachability.production.reachableSymbols.has(symbolId("src/lib.rs", "public_api")),
    ).toBe(true);
    expect(
      analysis.reachability.production.reachableSymbols.has(symbolId("src/lib.rs", "dead_helper")),
    ).toBe(false);
    expect(
      whyAlive({
        graph: analysis.graph,
        reachability: analysis.reachability,
        claims: analysis.result.claims,
        query: "dead_helper",
      }),
    ).toMatchObject({
      outcome: "dead",
      confidence: "high",
      evidence: [{ source: "rustc-dead-code" }],
    });
    expect(
      whyAlive({
        graph: analysis.graph,
        reachability: analysis.reachability,
        claims: analysis.result.claims,
        query: "public_api",
      }),
    ).toMatchObject({ outcome: "alive", entrypointKind: "production" });
  });

  it("keeps attributed runtime/linkage functions conservatively alive", async () => {
    const root = await mkdtemp(join(tmpdir(), "unused-rust-linkage-"));
    roots.push(root);
    await mkdir(join(root, "src"), { recursive: true });
    await writeFile(
      join(root, "Cargo.toml"),
      '[package]\nname = "neutral-linkage"\nversion = "0.1.0"\nedition = "2024"\n',
    );
    await writeFile(
      join(root, "Cargo.lock"),
      '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "neutral-linkage"\nversion = "0.1.0"\n',
    );
    await writeFile(
      join(root, "src", "lib.rs"),
      [
        "#[allow(dead_code)]",
        "#[unsafe(no_mangle)]",
        'unsafe extern "C" fn runtime_entry() {}',
        "",
        "#[inline]",
        "fn attributed_dead() {}",
        "",
      ].join("\n"),
    );

    const analysis = await analyzeRustProjectWithGraph(root, { now: new Date(0) });

    expect(analysis.result.claims).toEqual([]);
  });
});

function cargoPackage(name: string, manifestPath: string): CargoPackage {
  return {
    id: `neutral:${name}`,
    name,
    manifestPath,
    targets: [],
    features: {},
  };
}
